# Generated by Django 4.2.6 on 2023-10-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_alter_students_course_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_enrolled',
        ),
        migrations.AddField(
            model_name='courses',
            name='enrolled_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='studentApp.students'),
        ),
    ]
