# Generated by Django 4.2.6 on 2023-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_alter_courses_options_alter_students_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='user_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
