# Generated by Django 4.2.6 on 2023-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_alter_students_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='enrolled_student',
        ),
        migrations.AddField(
            model_name='courses',
            name='enrolled_students',
            field=models.ManyToManyField(null=True, related_name='student', to='studentApp.students'),
        ),
    ]
