# Generated by Django 4.2.6 on 2023-10-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0007_rename_enrolled_students_courses_enrolled_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='enrolled_student',
            field=models.ManyToManyField(null=True, related_name='Enroll_Courses', to='studentApp.students'),
        ),
    ]
