# Generated by Django 4.2.6 on 2023-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0009_alter_courses_enrolled_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='enrolled_student',
            field=models.ManyToManyField(null=True, related_name='enrolled', to='studentApp.students'),
        ),
    ]
